apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- amq-streams-operator-subscription.yaml
- kafka-cluster.yaml
- kafka-topic-vibration.yaml
- kafka-topic-temperature.yaml

- camel-k-operator-subscription.yaml
- camel-k-integration-platform.yaml
- mqtt2kafka-cm.yaml
- mqtt2kafka-integration.yaml
