apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: installplan-approver-role
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
rules:
- apiGroups: ["operators.coreos.com"]
  resources: ["installplans","subscriptions"]
  verbs: ["*"]

