apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: manuela-data-lake-central-s3-store

resources:
- manuela-data-lake-central-s3-store-namespace.yaml
- manuela-data-lake-central-s3-store-operatorgroup.yaml
- camel-k-operator-subscription.yaml
- camel-k-integration-platform.yaml
- kafka-to-s3-cm.yaml
- kafka-to-s3-integration.yaml
- s3-secret.yaml


bases:
- ../../../templates/manuela-team-rolebindings
- ../../../templates/installplan-approver
