apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  generateName: manuela-tst-all-
  generation: 1
  name: manuela-tst-all
  namespace: manuela-tst-all
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  targetNamespaces:
  - manuela-tst-all